import localFont from "next/font/local";
import "./globals.css";
import QueryClientWrapper from "@/components/common/QueryClientWrapper";
import MobileProtection from "@/components/common/MobileProtection";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
      >
        {/* This component disables viewing website on too small devices as It does not work on those. */}
        <MobileProtection />
        <QueryClientWrapper>{children}</QueryClientWrapper>
      </body>
    </html>
  );
}
